{
    "project": {
      "name": "jhead"
    },
    "name": "CVE-2020-26208",
    "binary": "/data/vulnloc/jhead/CVE-2020-26208/src/jhead",
    "crash": {
      "command": "$POC",
      "input": "/CrashRepair/experiments/vulnloc/jhead/CVE-2020-26208/tests/exploit",
      "bad_output": "SUMMARY: AddressSanitizer: heap-buffer-overflow",
      "extra-klee-flags": "",
      "expected-exit-code": 0,
      "halt-on-error": false
    },
    "source-directory": "src",
    "build": {
      "directory": "src",
      "binary": "/data/vulnloc/jhead/CVE-2020-26208/src/jhead",
      "sanitizerflags": "",
      "rebuild-for-validation": true,
      "commands": {
        "prebuild": "exit 0",
        "clean": "make clean",
        "build": "make CFLAGS=\"-fsanitize=address -fno-omit-frame-pointer -g\" CXXFLAGS=\"-fsanitize=address -fno-omit-frame-pointer -g\" LDFLAGS=\"-fsanitize=address\" -j10"
      }
    },
     "fuzzer": {
      "seed": 3,
      "crash-tag": "asan;1;jpgfile.c:285",
      "mutate-range": "default",
      "timeout": {
        "local": 300,
        "global": 300
      },
      "proof-of-crash": {
        "format": ["bfile"],
        "values": ["/CrashRepair/experiments/vulnloc/jhead/CVE-2020-26208/tests/exploit"],
        "commands": {
          "crash": ["/data/vulnloc/jhead/CVE-2020-26208/src/jhead", "***"],
          "trace": ["/data/vulnloc/jhead/CVE-2020-26208/src/jhead", "***"]
        }
      }
    }
  }
  